### PR TITLE
Fix some flattening pass errors

### LINKED ISSUE #303: Unification issue with struct type when defined via an inlined include
```
module attributes {veridise.lang = "llzk"} {
  module @FreeFuncModule {
    module @Level2A {
      module @Level3 {
        function.def @struct_param(%a: !struct.type<@StructModule::@Imported::@HasUse<[!felt.type]>>) -> !felt.type {
          %b = felt.const 42
          function.return %b: !felt.type
        }
      }
    }
    module @Level2B {
      module @Level3 {
        function.def @struct_param(%a: !struct.type<@StructModule::@Imported::@HasUse<[!felt.type]>>) -> !felt.type {
          %b = felt.const 42
          function.return %b: !felt.type
        }
      }
    }
  }

  module @StructModule {
    module @Imported attributes {veridise.lang = "llzk"} {
      struct.def @HasUse<[@T]> {
        function.def @compute() -> !struct.type<@HasUse<[@T]>> {
          %self = struct.new : !struct.type<@HasUse<[@T]>>
          function.return %self : !struct.type<@HasUse<[@T]>>
        }
        function.def @constrain(%arg0: !struct.type<@HasUse<[@T]>>) {
          function.return
        }
      }

      struct.def @NoUse {
        function.def @compute() -> !struct.type<@NoUse> {
          %self = struct.new : !struct.type<@NoUse>
          function.return %self : !struct.type<@NoUse>
        }
        function.def @constrain(%arg0: !struct.type<@NoUse>) {
          function.return
        }
      }
    }
  }
}
```

`Error on line 5: Cannot unify parameters of type '!struct.type<@StructModule::@Imported::@HasUse<[!felt.type]>>' with parameters of 'struct.def' "@HasUse<[@T]>"`

Also, the error message says the parameter list cannot unify but we're pretty sure it’s actually an issue that the base struct name is not matching.

See: `test/Transforms/Flattening/mastermind_included_with_main.llzk`

### PR DESCRIPTION
**Pull request by 0xddom**
Fixes issues related to the flattening pass and the handling of include ops.

Fixes #303, #305, VAN-286

### CODE REVIEW

File: lib/Util/TypeHelper.cpp [hunk 1]
```diff
@@ -863,12 +889,14 @@ bool structTypesUnify(
...
     Type lhs, Type rhs, ArrayRef<StringRef> rhsReversePrefix, UnificationMap *unifications
 ) {
+
   return UnifierImpl(unifications, rhsReversePrefix).typesUnify(lhs, rhs);
 }
 
 bool isMoreConcreteUnification(
     Type oldTy, Type newTy, llvm::function_ref<bool(Type oldTy, Type newTy)> knownOldToNew
 ) {
+
```
Comment (iangneal) [inline lib/Util/TypeHelper.cpp]:
```suggestion
```

**Review by iangneal — COMMENTED** [review]
Overall LGTM, just a few comments. Also CI needs to be fixed.
